# Generated by Django 4.1.7 on 2023-02-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=100000)),
                ('date', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.company')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('block_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('textBlock', models.TextField(blank=True, max_length=255)),
                ('sa_value', models.FloatField()),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.text')),
                ('theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.theme')),
            ],
        ),
    ]
