# Generated by Django 4.1.7 on 2023-02-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_description',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
