# Generated by Django 4.1.7 on 2023-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_platform_platform_url_theme_theme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
