# Generated by Django 4.1.7 on 2023-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_text_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='platform_id',
        ),
        migrations.AddField(
            model_name='text',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
