# Generated by Django 4.1.7 on 2023-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_text_platform_id_text_rating_delete_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
