# Generated by Django 4.1.7 on 2023-06-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_rename_user_id_theme_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='user',
        ),
    ]
