# Generated by Django 4.1.7 on 2023-06-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_theme_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='user',
            new_name='user_id',
        ),
    ]
