# Generated by Django 4.1.7 on 2023-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_company_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
