# Generated by Django 4.1.7 on 2023-06-05 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0016_company_is_public'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextBlock',
            new_name='ReviewTextBlock',
        ),
        migrations.CreateModel(
            name='SetOfText',
            fields=[
                ('set_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='set_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.setoftext'),
        ),
    ]
