# Generated by Django 4.1.7 on 2023-06-07 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_rename_textblock_reviewtextblock_setoftext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.company'),
            preserve_default=False,
        ),
    ]
