# Generated by Django 4.1.7 on 2023-06-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_rename_user_id_company_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoftext',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
    ]
