# Generated by Django 4.1.7 on 2023-06-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtextblock',
            name='sa_value',
            field=models.TextField(),
        ),
    ]
