# Generated by Django 4.1.7 on 2023-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_alter_model_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoftext',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
