# Generated by Django 4.1.7 on 2023-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_setoftext_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewtextblock',
            name='textBlock',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
